### PR TITLE
✨ [Issue-6] Build Data model for Home Page

### LINKED ISSUE #6: [Feature] - Build data model for Home Page in CMS
Given strapi has now been integrated into the Front End we need to create a data model for populating data on the home page so it can be controlled via the CMS, rather than in code.

Looking at the home page design, at least the following will be required (to be updated during development):

- [ ] Heading
- [ ] Sub-heading
- [ ] Current Status Content Block (might make sense as a component in Strapi TB)
- [ ] Values (might make sense as a component in Strapi
- [ ] Mission
- [ ] Goals
- [x] Partner data for "Our partners section
- [ ] Footer (might make sense as a Strapi component)
- [ ] meta og content
  - [ ] title (max 50–60 characters)
  - [ ] description (max length 155-160 characters)
  - [ ] image (1200:630px)

Unsure if we hard code/not the image of the explorers etc. in the hero above the fold but leaving this here as a reminder.

It may make sense to build a few of these as Components content types in Strapi but don't know enough about this feature to make that call right now. Documentation is [here](https://docs.strapi.io/user-docs/latest/content-types-builder/creating-new-content-type.html#creating-a-new-content-type).

### PR DESCRIPTION
**Pull request by andriishupta**
Closes #6 

- add Open Graph component
- add Statement component
- add Link component
- add Current Status component
- add news_ticker to Home Page
- add missions to Home Page
- add values to Home Page
- add goals to Home Page
- add heading to Home Page
- add sub_heading to Home Page
- add current_status to Home Page

## Screenshots
image
image
image
image
image

### CODE REVIEW

**Comment by andriishupta** [comment]
current_status block:
image

**Comment by andriishupta** [comment]
- add Seeding For Home Page
- 👽 add utility for uploading media files without REST API - taken from Strapi's source code

image
image
image
image

**Comment by andriishupta** [comment]
did 2 small code updates that doesn't affect logic - forced pushed changes

**Comment by andriishupta** [comment]
removed `home_page: true` indicator, such as Single Collection always has only 1 instance of Home Page

**Review by mhmulford0 — APPROVED** [review]

**Comment by mhmulford0** [comment]
Amazing work as always. I have checked this against the recent changes and everything looks great. merged

**Comment by andriishupta** [comment]
Thanks!

**Pull request merged**
